name: OpenAPI Generator - Code Generation

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install @openapitools/openapi-generator-cli -g
    - run: openapi-generator-cli generate
    - name: Upload library
      uses: 'actions/upload-artifact@v2'
      with:
        name: klauke-enterprises-api-clients
        path: build/**
  upload:
    runs-on: ubuntu-latest
    needs:
      - generate
    strategy:
      matrix:
        library:
          - java
          - ts
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          name: klauke-enterprises-api-clients
          path: build
      - name: Upload library
        uses: 'actions/upload-artifact@v2'
        with:
          name: klauke-enterprises-api-client-${{ matrix.library }}
          path: build/${{ matrix.library }}/
  package-protocol-spring:
    runs-on: ubuntu-latest
    needs:
      - generate
    defaults:
      run:
        working-directory: pkg/protocol-spring
    steps:
      - uses: actions/checkout@v2
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          name: klauke-enterprises-api-clients
          path: build
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: .gradle/caches
          key: gradle-cache
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_GPG_KEY: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: protocol-spring
          path: pkg/protocol-spring/build/libs/*
      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_GPG_KEY: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
  package-ts-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build/ts
    needs:
      - generate
    steps:
      - uses: actions/checkout@v2
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          name: klauke-enterprises-api-clients
          path: build
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
      - run: npm install
      - run: npm build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
