name: OpenAPI Generator - Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@v1
      with:
        output: docs
        spec-file: klauke-enterprises-api.v3.yaml
    - name: Deploy Documentation
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: docs
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
