name: OpenAPI Generator

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          definition-file: klauke-enterprises-api.v3.yaml

  generate:
    runs-on: ubuntu-latest
    needs:
      - validate
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 12.x
      - run: npm install @openapitools/openapi-generator-cli -g
      - run: openapi-generator-cli generate
      - name: Upload library
        uses: 'actions/upload-artifact@v2'
        with:
          name: klauke-enterprises-api-clients
          path: build/**

  upload:
    runs-on: ubuntu-latest
    needs:
      - generate
    strategy:
      matrix:
        library:
          - java
          - ts
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          name: klauke-enterprises-api-clients
          path: build
      - name: Upload library
        uses: 'actions/upload-artifact@v2'
        with:
          name: klauke-enterprises-api-client-${{ matrix.library }}
          path: build/${{ matrix.library }}/
